"""initial immutable ownership and settlement ledger"""
from alembic import op
import sqlalchemy as sa

revision = '9df9e14d4a6c'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=False),
    sa.Column('adapter', sa.String(length=80), nullable=False),
    sa.Column('seller_user_id', sa.String(length=32), nullable=False),
    sa.Column('token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_hint', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('health', sa.String(length=32), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('stats_config', sa.JSON(), nullable=False),
    sa.Column('collect_enabled', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('superadmin','admin','user')", name='ck_user_role'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_parent_id'), 'users', ['parent_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('announcements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title_zh', sa.String(length=200), nullable=False),
    sa.Column('content_zh', sa.Text(), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('audience', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.String(length=36), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=60), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_object_id'), 'audit_events', ['object_id'], unique=False)
    op.create_table('credential_formats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schema_config', sa.JSON(), nullable=False),
    sa.Column('default_models', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'code', 'version', name='uq_format_version')
    )
    op.create_index(op.f('ix_credential_formats_category_id'), 'credential_formats', ['category_id'], unique=False)
    op.create_table('discount_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payer_id', sa.String(length=36), nullable=False),
    sa.Column('payee_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('percent', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_versions_category_id'), 'discount_versions', ['category_id'], unique=False)
    op.create_index(op.f('ix_discount_versions_payee_id'), 'discount_versions', ['payee_id'], unique=False)
    op.create_index(op.f('ix_discount_versions_payer_id'), 'discount_versions', ['payer_id'], unique=False)
    op.create_table('model_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('valid_hours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pricing_unit', sa.String(length=40), nullable=False),
    sa.Column('payment_unit', sa.String(length=40), nullable=False),
    sa.Column('factor', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('precision', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_reads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('announcement_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'announcement_id', 'version', name='uq_announcement_read')
    )
    op.create_index(op.f('ix_announcement_reads_announcement_id'), 'announcement_reads', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_reads_user_id'), 'announcement_reads', ['user_id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('payer_id', sa.String(length=36), nullable=False),
    sa.Column('payee_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('category_name', sa.String(length=160), nullable=False),
    sa.Column('payer_name', sa.String(length=160), nullable=False),
    sa.Column('payee_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('pricing_unit', sa.String(length=40), nullable=False),
    sa.Column('payment_unit', sa.String(length=40), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('pricing_amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('payment_rule_id', sa.String(length=36), nullable=True),
    sa.Column('payment_factor', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirm_key', sa.String(length=100), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_rule_id'], ['payment_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirm_key'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_bills_category_id'), 'bills', ['category_id'], unique=False)
    op.create_index(op.f('ix_bills_layer'), 'bills', ['layer'], unique=False)
    op.create_index(op.f('ix_bills_payee_id'), 'bills', ['payee_id'], unique=False)
    op.create_index(op.f('ix_bills_payer_id'), 'bills', ['payer_id'], unique=False)
    op.create_index(op.f('ix_bills_status'), 'bills', ['status'], unique=False)
    op.create_table('upload_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('format_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['format_id'], ['credential_formats.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_index(op.f('ix_upload_groups_owner_id'), 'upload_groups', ['owner_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('storage_name', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_name')
    )
    op.create_index(op.f('ix_attachments_bill_id'), 'attachments', ['bill_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('format_id', sa.String(length=36), nullable=False),
    sa.Column('key_encrypted', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=100), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('declaration', sa.Text(), nullable=False),
    sa.Column('proxy_encrypted', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['format_id'], ['credential_formats.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['upload_groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'fingerprint', name='uq_channel_owner_fingerprint')
    )
    op.create_index(op.f('ix_channels_category_id'), 'channels', ['category_id'], unique=False)
    op.create_index(op.f('ix_channels_fingerprint'), 'channels', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_channels_group_id'), 'channels', ['group_id'], unique=False)
    op.create_index(op.f('ix_channels_owner_id'), 'channels', ['owner_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('payer_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('payment_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('network', sa.String(length=100), nullable=False),
    sa.Column('transaction_id', sa.String(length=200), nullable=False),
    sa.Column('recipient_account', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('payer_id', 'network', 'transaction_id', name='uq_payment_transaction')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('execution_actor_id', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('actor_session_version', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('request_hash', sa.String(length=128), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['execution_actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['upload_groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'idempotency_key', name='uq_task_actor_idempotency')
    )
    op.create_index(op.f('ix_tasks_actor_id'), 'tasks', ['actor_id'], unique=False)
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks', ['owner_id'], unique=False)
    op.create_table('distributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('remote_id', sa.String(length=80), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('remote_name', sa.String(length=160), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('routing_group', sa.String(length=160), nullable=False),
    sa.Column('remote_snapshot', sa.JSON(), nullable=False),
    sa.Column('test_status', sa.String(length=40), nullable=False),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.Column('usage_status', sa.String(length=40), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('adopted_at', sa.DateTime(), nullable=True),
    sa.Column('adoption_baseline', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'site_id', name='uq_distribution_channel_site'),
    sa.UniqueConstraint('site_id', 'remote_id', name='uq_distribution_site_remote')
    )
    op.create_index(op.f('ix_distributions_channel_id'), 'distributions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_distributions_site_id'), 'distributions', ['site_id'], unique=False)
    op.create_table('key_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('key_encrypted', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'version', name='uq_key_channel_version')
    )
    op.create_index(op.f('ix_key_versions_channel_id'), 'key_versions', ['channel_id'], unique=False)
    op.create_table('unclaimed_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('remote_id', sa.String(length=80), nullable=False),
    sa.Column('remote_name', sa.String(length=160), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('adopted_channel_id', sa.String(length=36), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adopted_channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'remote_id', name='uq_unclaimed_site_remote')
    )
    op.create_index(op.f('ix_unclaimed_channels_site_id'), 'unclaimed_channels', ['site_id'], unique=False)
    op.create_table('distribution_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('distribution_id', sa.String(length=36), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_versions_distribution_id'), 'distribution_versions', ['distribution_id'], unique=False)
    op.create_table('task_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('distribution_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_items_channel_id'), 'task_items', ['channel_id'], unique=False)
    op.create_index(op.f('ix_task_items_site_id'), 'task_items', ['site_id'], unique=False)
    op.create_index(op.f('ix_task_items_status'), 'task_items', ['status'], unique=False)
    op.create_index(op.f('ix_task_items_task_id'), 'task_items', ['task_id'], unique=False)
    op.create_table('usage_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('distribution_id', sa.String(length=36), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('raw_amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('raw_unit', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('conversion_version', sa.String(length=120), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'distribution_id', 'source_id', name='uq_usage_source')
    )
    op.create_index(op.f('ix_usage_facts_admin_id'), 'usage_facts', ['admin_id'], unique=False)
    op.create_index(op.f('ix_usage_facts_category_id'), 'usage_facts', ['category_id'], unique=False)
    op.create_index(op.f('ix_usage_facts_channel_id'), 'usage_facts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_usage_facts_distribution_id'), 'usage_facts', ['distribution_id'], unique=False)
    op.create_index(op.f('ix_usage_facts_occurred_at'), 'usage_facts', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_usage_facts_owner_id'), 'usage_facts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_usage_facts_site_id'), 'usage_facts', ['site_id'], unique=False)
    op.create_table('usage_samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('distribution_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('delta', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distribution_id', 'source_id', name='uq_usage_sample')
    )
    op.create_table('adjustments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fact_id'], ['usage_facts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_adjustments_bill_id'), 'adjustments', ['bill_id'], unique=False)
    op.create_table('bill_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('percent', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('pricing_amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('discount_id', sa.String(length=36), nullable=True),
    sa.Column('original_discount_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['discount_id'], ['discount_versions.id'], ),
    sa.ForeignKeyConstraint(['fact_id'], ['usage_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_lines_bill_id'), 'bill_lines', ['bill_id'], unique=False)
    op.create_table('settlement_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('payer_id', sa.String(length=36), nullable=False),
    sa.Column('payee_id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('bill_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['fact_id'], ['usage_facts.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layer', 'payer_id', 'payee_id', 'fact_id', name='uq_settlement_fact_claim')
    )
    op.create_index(op.f('ix_settlement_claims_bill_id'), 'settlement_claims', ['bill_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_claims_bill_id'), table_name='settlement_claims')
    op.drop_table('settlement_claims')
    op.drop_index(op.f('ix_bill_lines_bill_id'), table_name='bill_lines')
    op.drop_table('bill_lines')
    op.drop_index(op.f('ix_adjustments_bill_id'), table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_table('usage_samples')
    op.drop_index(op.f('ix_usage_facts_site_id'), table_name='usage_facts')
    op.drop_index(op.f('ix_usage_facts_owner_id'), table_name='usage_facts')
    op.drop_index(op.f('ix_usage_facts_occurred_at'), table_name='usage_facts')
    op.drop_index(op.f('ix_usage_facts_distribution_id'), table_name='usage_facts')
    op.drop_index(op.f('ix_usage_facts_channel_id'), table_name='usage_facts')
    op.drop_index(op.f('ix_usage_facts_category_id'), table_name='usage_facts')
    op.drop_index(op.f('ix_usage_facts_admin_id'), table_name='usage_facts')
    op.drop_table('usage_facts')
    op.drop_index(op.f('ix_task_items_task_id'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_status'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_site_id'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_channel_id'), table_name='task_items')
    op.drop_table('task_items')
    op.drop_index(op.f('ix_distribution_versions_distribution_id'), table_name='distribution_versions')
    op.drop_table('distribution_versions')
    op.drop_index(op.f('ix_unclaimed_channels_site_id'), table_name='unclaimed_channels')
    op.drop_table('unclaimed_channels')
    op.drop_index(op.f('ix_key_versions_channel_id'), table_name='key_versions')
    op.drop_table('key_versions')
    op.drop_index(op.f('ix_distributions_site_id'), table_name='distributions')
    op.drop_index(op.f('ix_distributions_channel_id'), table_name='distributions')
    op.drop_table('distributions')
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_actor_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('payments')
    op.drop_index(op.f('ix_channels_owner_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_group_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_fingerprint'), table_name='channels')
    op.drop_index(op.f('ix_channels_category_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_attachments_bill_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_upload_groups_owner_id'), table_name='upload_groups')
    op.drop_table('upload_groups')
    op.drop_index(op.f('ix_bills_status'), table_name='bills')
    op.drop_index(op.f('ix_bills_payer_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_payee_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_layer'), table_name='bills')
    op.drop_index(op.f('ix_bills_category_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_announcement_reads_user_id'), table_name='announcement_reads')
    op.drop_index(op.f('ix_announcement_reads_announcement_id'), table_name='announcement_reads')
    op.drop_table('announcement_reads')
    op.drop_table('payment_rules')
    op.drop_table('model_targets')
    op.drop_index(op.f('ix_discount_versions_payer_id'), table_name='discount_versions')
    op.drop_index(op.f('ix_discount_versions_payee_id'), table_name='discount_versions')
    op.drop_index(op.f('ix_discount_versions_category_id'), table_name='discount_versions')
    op.drop_table('discount_versions')
    op.drop_index(op.f('ix_credential_formats_category_id'), table_name='credential_formats')
    op.drop_table('credential_formats')
    op.drop_index(op.f('ix_audit_events_object_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_parent_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('sites')
    op.drop_table('categories')
    # ### end Alembic commands ###
